// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bayamo.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/bayamo.proto

It has these top-level messages:
	DownloadJob
	DownloadJobResult
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DownloadJob struct {
	Url       string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	OutputDir string `protobuf:"bytes,2,opt,name=outputDir" json:"outputDir,omitempty"`
}

func (m *DownloadJob) Reset()                    { *m = DownloadJob{} }
func (m *DownloadJob) String() string            { return proto1.CompactTextString(m) }
func (*DownloadJob) ProtoMessage()               {}
func (*DownloadJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DownloadJob) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadJob) GetOutputDir() string {
	if m != nil {
		return m.OutputDir
	}
	return ""
}

type DownloadJobResult struct {
	Ok         bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	OutputPath string `protobuf:"bytes,2,opt,name=outputPath" json:"outputPath,omitempty"`
}

func (m *DownloadJobResult) Reset()                    { *m = DownloadJobResult{} }
func (m *DownloadJobResult) String() string            { return proto1.CompactTextString(m) }
func (*DownloadJobResult) ProtoMessage()               {}
func (*DownloadJobResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DownloadJobResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *DownloadJobResult) GetOutputPath() string {
	if m != nil {
		return m.OutputPath
	}
	return ""
}

func init() {
	proto1.RegisterType((*DownloadJob)(nil), "proto.DownloadJob")
	proto1.RegisterType((*DownloadJobResult)(nil), "proto.DownloadJobResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DownloaderService service

type DownloaderServiceClient interface {
	Write(ctx context.Context, in *DownloadJob, opts ...grpc.CallOption) (*DownloadJobResult, error)
}

type downloaderServiceClient struct {
	cc *grpc.ClientConn
}

func NewDownloaderServiceClient(cc *grpc.ClientConn) DownloaderServiceClient {
	return &downloaderServiceClient{cc}
}

func (c *downloaderServiceClient) Write(ctx context.Context, in *DownloadJob, opts ...grpc.CallOption) (*DownloadJobResult, error) {
	out := new(DownloadJobResult)
	err := grpc.Invoke(ctx, "/proto.DownloaderService/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DownloaderService service

type DownloaderServiceServer interface {
	Write(context.Context, *DownloadJob) (*DownloadJobResult, error)
}

func RegisterDownloaderServiceServer(s *grpc.Server, srv DownloaderServiceServer) {
	s.RegisterService(&_DownloaderService_serviceDesc, srv)
}

func _DownloaderService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DownloaderService/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServiceServer).Write(ctx, req.(*DownloadJob))
	}
	return interceptor(ctx, in, info, handler)
}

var _DownloaderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DownloaderService",
	HandlerType: (*DownloaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _DownloaderService_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bayamo.proto",
}

func init() { proto1.RegisterFile("proto/bayamo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4a, 0xac, 0x4c, 0xcc, 0xcd, 0xd7, 0x03, 0x73, 0x84, 0x58, 0xc1, 0x94, 0x92,
	0x2d, 0x17, 0xb7, 0x4b, 0x7e, 0x79, 0x5e, 0x4e, 0x7e, 0x62, 0x8a, 0x57, 0x7e, 0x92, 0x90, 0x00,
	0x17, 0x73, 0x69, 0x51, 0x8e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x29, 0x24, 0xc3,
	0xc5, 0x99, 0x5f, 0x5a, 0x52, 0x50, 0x5a, 0xe2, 0x92, 0x59, 0x24, 0xc1, 0x04, 0x16, 0x47, 0x08,
	0x28, 0x39, 0x73, 0x09, 0x22, 0x69, 0x0f, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x11, 0xe2, 0xe3, 0x62,
	0xca, 0xcf, 0x06, 0x9b, 0xc1, 0x11, 0xc4, 0x94, 0x9f, 0x2d, 0x24, 0xc7, 0xc5, 0x05, 0xd1, 0x11,
	0x90, 0x58, 0x92, 0x01, 0x35, 0x03, 0x49, 0xc4, 0xc8, 0x07, 0x61, 0x48, 0x6a, 0x51, 0x70, 0x6a,
	0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x39, 0x17, 0x6b, 0x78, 0x51, 0x66, 0x49, 0xaa, 0x90, 0x10,
	0xc4, 0xc1, 0x7a, 0x48, 0xf6, 0x48, 0x49, 0x60, 0x8a, 0x41, 0xec, 0x56, 0x62, 0x48, 0x62, 0x03,
	0x4b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x83, 0x77, 0x3e, 0x1e, 0xf5, 0x00, 0x00, 0x00,
}
